name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/sepio-classifier:latest .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/sepio-classifier:latest

    #- name: Azure login
     # uses: azure/login@v2
      #with:
       #   client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    #- name: 'Deploy to Azure Web App'
     # uses: azure/webapps-deploy@v2
      #with:
       # app-name: 'sepio-classifier'
        #slot-name: 'production'
        #images: '${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/sepio-classifier:latest'

    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sepio-classifier'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/sepio-classifier:latest'
